# Generated by Django 4.1.5 on 2023-02-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association_details',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='developer_details',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
